[package]
name = "simple"
version = "0.0.1"
edition = "2021"
publish = false

[dev-dependencies]
ememdb_rs = { version="0.1", path = "../ememdb_rs" }
serde_json = "1.0"
uuid = "1.10.2"

[[example]]
name = "simple"
path = "simple.rs"
