[package]
name = "simple"
version = "0.0.1"
edition = "2021"
publish = false

[dev-dependencies]
ememdb_rs = { version="0.1", path = "../ememdb_rs" }
uuid = "1.10.2"
postgrest = "1.6.0"
dotenv = "0.15.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.107"
serde_derive = "1.0"
clap = {version = "3.0.0", features = ["derive"]}
[[example]]
name = "simple"
path = "simple.rs"
